Repository LorenFrankLab/spyglass, pull requests merged in 2022-10, with the labels that each got.

#360 Address issue #359 add filter_type to filterdict
  src/spyglass/common/common_filter.py
Labels: bug

#355 num jobs = 8 for SpikeSortingRecording.populate()
  src/spyglass/spikesorting/spikesorting_recording.py
Labels: spike sorting

#366 Add method to VideoFile to return absolute path based on environment variable
  src/spyglass/common/common_behav.py
Labels: bug, enhancement
