Repository LorenFrankLab/spyglass, pull requests merged in 2023-05, with the labels that each got.

#468 Lfp_v1_lf
  notebooks/3_lfp.ipynb
  src/spyglass/lfp/v1/__init__.py
  src/spyglass/lfp/v1/lfp.py
Labels: enhancement

#473 LFP artifact detect
  src/spyglass/lfp/v1/__init__.py
  src/spyglass/lfp/v1/lfp.py
Labels: enhancement

#502 Make fixes to spyglass-position env creation and catch centroid cases
  environment_position.yml
  src/spyglass/position/v1/position_dlc_centroid.py
Labels: bug, position

#505 Add DLC schema images for Tutorial notebooks
  .gitignore
  notebooks/dlc_existing.png
  notebooks/dlc_scratch.png
Labels: position
