Repository LorenFrankLab/spyglass, pull requests merged in 2024-04, with the labels that each got.

#875 Export logger
  CHANGELOG.md
  docs/mkdocs.yml
  docs/src/misc/export.md
  notebooks/05_Export.ipynb
  notebooks/py_scripts/05_Export.py
  src/spyglass/common/common_lab.py
  src/spyglass/common/common_usage.py
  src/spyglass/settings.py
  src/spyglass/utils/dj_graph.py
  src/spyglass/utils/dj_helper_fn.py
  src/spyglass/utils/dj_merge_tables.py
  src/spyglass/utils/dj_mixin.py
Labels: enhancement, infrastructure

#910 Spikesorting quality of life helpers
  CHANGELOG.md
  notebooks/10_Spike_SortingV1.ipynb
  notebooks/40_Extracting_Clusterless_Waveform_Features.ipynb
  notebooks/41_Decoding_Clusterless.ipynb
  notebooks/42_Decoding_SortedSpikes.ipynb
  notebooks/py_scripts/10_Spike_SortingV1.py
  notebooks/py_scripts/40_Extracting_Clusterless_Waveform_Features.py
  notebooks/py_scripts/41_Decoding_Clusterless.py
  notebooks/py_scripts/42_Decoding_SortedSpikes.py
  src/spyglass/spikesorting/spikesorting_merge.py
  src/spyglass/spikesorting/v0/spikesorting_curation.py
  src/spyglass/spikesorting/v0/spikesorting_sorting.py
  src/spyglass/spikesorting/v1/curation.py
  src/spyglass/spikesorting/v1/sorting.py
Labels: spike sorting

#937 Add logging of AnalysisNwbfile creation time and file size
  CHANGELOG.md
  src/spyglass/common/common_ephys.py
  src/spyglass/common/common_nwbfile.py
  src/spyglass/common/common_position.py
  src/spyglass/decoding/v0/clusterless.py
  src/spyglass/decoding/v1/waveform_features.py
  src/spyglass/lfp/analysis/v1/lfp_band.py
  src/spyglass/lfp/v1/lfp.py
  src/spyglass/linearization/v0/main.py
  src/spyglass/linearization/v1/main.py
  src/spyglass/position/v1/position_dlc_centroid.py
  src/spyglass/position/v1/position_dlc_orient.py
  src/spyglass/position/v1/position_dlc_pose_estimation.py
  src/spyglass/position/v1/position_dlc_position.py
  src/spyglass/position/v1/position_dlc_selection.py
  src/spyglass/position/v1/position_trodes_position.py
  src/spyglass/spikesorting/v0/spikesorting_curation.py
  src/spyglass/spikesorting/v1/curation.py
  src/spyglass/spikesorting/v1/metric_curation.py
  src/spyglass/spikesorting/v1/recording.py
  src/spyglass/spikesorting/v1/sorting.py
  src/spyglass/utils/dj_mixin.py
Labels: infrastructure
